package com.rk.constants;

public enum Role {
	ADMIN, MANAGER, STAFF, GUEST,RECEPTIONIST, HOUSEKEEPING, CHEF, MAINTENANCE, SECURITY,
	INVENTORY,PR,ANALYSER,EVENTMANAGEMENT,MARKETING ,SUPPORT ,SALES, HR
}
